### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by dillfrescott** [positive-intentions/chat#118]
How to leave pods and how to delete a contact?

**Comment by xoron** [comment]
unfortunately those features havent been implemented.

leaving a pod - this isnt being looked at at the moment in favour of other details. sorry.

deleting a contact - (word vomit alert) this issue is quite tricky and is being investigated separately as part of of is needed for a production-grade version of the app. i think i would like to aim for something like a "block contact" button. the way the app works with the peerjs-server, storing peerId's of known/authenticated peers it makes "blocking" a contact require a regeneration of your own ID to make it so the blocked peer isnt able to ping you.
